name: gphs445
channels:
  - conda-forge
  - defaults
dependencies:
  - asn1crypto=0.24.0=py37_1003
  - attrs=19.1.0=py_0
  - backcall=0.1.0=py_0
  - basemap=1.2.0=py37h673bf1a_1001
  - blas=1.0=mkl
  - bleach=3.1.0=py_0
  - bzip2=1.0.6=h14c3975_1002
  - ca-certificates=2018.11.29=ha4d7672_0
  - certifi=2018.11.29=py37_1000
  - cffi=1.12.2=py37h9745a5d_0
  - chardet=3.0.4=py37_1003
  - cryptography=2.5=py37h9d9f1b6_1
  - cycler=0.10.0=py_1
  - dbus=1.13.2=h714fa37_1
  - decorator=4.3.2=py_0
  - defusedxml=0.5.0=py_1
  - entrypoints=0.3=py37_1000
  - expat=2.2.5=hf484d3e_1002
  - fontconfig=2.13.1=h2176d3f_1000
  - freetype=2.9.1=h94bbf69_1005
  - future=0.17.1=py37_1000
  - geos=3.7.1=hf484d3e_1000
  - gettext=0.19.8.1=h9745a5d_1001
  - glib=2.56.2=had28632_1001
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - icu=58.2=hf484d3e_1000
  - idna=2.8=py37_1000
  - intel-openmp=2019.1=144
  - ipykernel=5.1.0=py37h24bf2e0_1002
  - ipython=7.3.0=py37h24bf2e0_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.4.2=py_0
  - jedi=0.13.3=py37_0
  - jinja2=2.10=py_1
  - jpeg=9c=h14c3975_1001
  - jsonschema=3.0.1=py37_0
  - jupyter=1.0.0=py_1
  - jupyter_client=5.2.4=py_3
  - jupyter_console=6.0.0=py_0
  - jupyter_core=4.4.0=py_0
  - jupyterlab=0.35.4=py37_0
  - jupyterlab_server=0.2.0=py_0
  - kiwisolver=1.0.1=py37h6bb024c_1002
  - libffi=3.2.1=hf484d3e_1005
  - libgcc-ng=7.3.0=hdf63c60_0
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libiconv=1.15=h14c3975_1004
  - libpng=1.6.36=h84994c4_1000
  - libsodium=1.0.16=h14c3975_1001
  - libstdcxx-ng=7.3.0=hdf63c60_0
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.8=h143f9aa_1005
  - libxslt=1.1.32=h4785a14_1002
  - lxml=4.3.2=py37h23eabaa_0
  - markupsafe=1.1.1=py37h14c3975_0
  - matplotlib=3.0.3=py37_0
  - matplotlib-base=3.0.3=py37h167e16e_0
  - mistune=0.8.4=py37h14c3975_1000
  - mkl=2019.1=144
  - mkl_fft=1.0.10=py37h14c3975_1
  - mkl_random=1.0.2=py37h637b7d7_2
  - nbconvert=5.4.1=py_2
  - nbformat=4.4.0=py_1
  - ncurses=6.1=hf484d3e_1002
  - notebook=5.7.5=py37_0
  - numpy=1.16.2=py37h7e9f1db_0
  - numpy-base=1.16.2=py37hde5b4d6_0
  - obspy=1.1.1=py37h3010b51_0
  - openssl=1.1.1b=h14c3975_0
  - pandoc=2.6=1
  - pandocfilters=1.4.2=py_1
  - parso=0.3.4=py_0
  - pcre=8.42=h439df22_0
  - pexpect=4.6.0=py37_1000
  - pickleshare=0.7.5=py37_1000
  - pip=19.0.3=py37_0
  - proj4=4.9.3=h470a237_8
  - prometheus_client=0.6.0=py_0
  - prompt_toolkit=2.0.9=py_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py37_1000
  - pycparser=2.19=py_0
  - pygments=2.3.1=py_0
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.3.1=py_0
  - pyproj=1.9.5.1=py37h2944ce7_1006
  - pyqt=5.6.0=py37h13b7fb3_1008
  - pyrsistent=0.14.11=py37h14c3975_0
  - pyshp=2.1.0=py_0
  - pysocks=1.6.8=py37_1002
  - python=3.7.1=h381d211_1002
  - python-dateutil=2.8.0=py_0
  - pyzmq=18.0.1=py37h0e1adb2_0
  - qt=5.6.3=h8bf5577_3
  - qtconsole=4.4.3=py_0
  - readline=7.0=hf8c457e_1001
  - requests=2.21.0=py37_1000
  - scipy=1.2.1=py37h7c811a0_0
  - send2trash=1.5.0=py_0
  - setuptools=40.8.0=py37_0
  - sip=4.18.1=py37hf484d3e_1000
  - six=1.12.0=py37_1000
  - sqlalchemy=1.3.0=py37h14c3975_0
  - sqlite=3.26.0=h67949de_1000
  - terminado=0.8.1=py37_1001
  - testpath=0.4.2=py37_1000
  - tk=8.6.9=h84994c4_1000
  - tornado=6.0.1=py37h14c3975_0
  - traitlets=4.3.2=py37_1000
  - urllib3=1.24.1=py37_1000
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - wheel=0.33.1=py37_0
  - widgetsnbextension=3.4.2=py37_1000
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.2=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - zeromq=4.2.5=hf484d3e_1006
  - zlib=1.2.11=h14c3975_1004
prefix: /home/calumch/miniconda3/envs/gphs445
